# Generated by Django 4.2.28 on 2026-02-21 10:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'menu_item', 'order')},
        ),
    ]
